baseURL = 'https://quantpoet.github.io/'
languageCode = 'en-us'
title = 'Quantitative Poetry'
theme = "texify"
licenselink = "https://github.com/francescotonini/texify/blob/master/LICENSE"
description = "A minimal, latex-style hugo theme for personal blogging"
homepage = "https://quantpoet.github.io/home"
tags = ["blog", "clean", "latex", "light", "minimal", "responsive", "simple"]
features = ["blog"]
min_version = "0.60"

[author]
  name = "Charaf ZGUIOUAR"
  homepage = ""

